---
- hosts: all
  become: yes
  vars:
    docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
    kubernetes_gpg_url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    pod_network_cidr: "10.244.0.0/16"

  tasks:
    - name: Update apt packages
      apt:
        update_cache: No

    - name: Install necessary packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present

    - name: Add Docker GPG key
      get_url:
        url: "{{ docker_gpg_url }}"
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] | lower }} stable"
        create: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: No

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add Kubernetes GPG key
      get_url:
        url: "{{ kubernetes_gpg_url }}"
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes repository
      copy:
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
        dest: /etc/apt/sources.list.d/kubernetes.list

    - name: Install Kubernetes components
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: No

    - name: Hold Kubernetes packages
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        force: yes
        allow_unauthenticated: yes
        upgrade: no

- hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes control plane
      command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
      register: kubeadm_init

    - name: Save kubeadm join command
      copy:
        dest: /tmp/kubeadm_join.sh
        content: |
          {{ kubeadm_init.stdout_lines | select("match", "kubeadm join") | join('\n') }}
        mode: '0700'

    - name: Set up kubectl for root user
      command: >
        bash -c "mkdir -p $HOME/.kube &&
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config &&
        chown $(id -u):$(id -g) $HOME/.kube/config"

    - name: Deploy Calico network
      command: kubectl apply -f https://docs.projectcalico.org/v3.21/manifests/calico.yaml

- hosts: workers
  become: yes
  tasks:
    - name: Join worker nodes to cluster
      shell: bash /tmp/kubeadm_join.sh
      args:
        executable: /bin/bash
